baseurl = "https://harrycresswell.com/"
theme = "hc-starter"
languageCode = "en-gb"
title = "Michael Babwahsingh"
pluralizelisttitles = false
# Enable for syntax highlighting
pygmentsUseClasses = true
# Enable highlighting for code fences
pygmentsCodeFences = true
# Get LastMod data from Git
enableGitInfo = true

# Enable Emojis
enableEmoji = true

[params]
keywords = "Product Design, UX Design, UI Design, Front-end Web Development, Small businesses, Automation, Typography"
description = ""
strapline = "XX"
location = "XX"
card_image = "img/card-image.png"
dateFormat = "02 Jan 2006"

[params.author]
name = "Michael Babwahsingh"
email = "XX"
github = ""
linkedin = ""

[taxonomies]
category = "categories"

[outputs]
home = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[permalinks]
writing = "/:section/:slug/"
projects = "/:section/:slug/"
updates = "/:section/:slug/"
page = "/:slug/"

[markup]
[markup.goldmark]
duplicateResourceFiles = false
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true
[markup.goldmark.extensions.extras]
[markup.goldmark.extensions.extras.insert]
enable = false
[markup.goldmark.extensions.extras.mark]
enable = true
[markup.goldmark.extensions.extras.subscript]
enable = false
[markup.goldmark.extensions.extras.superscript]
enable = false
[markup.goldmark.extensions.passthrough]
enable = false
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false # remove paragraphs that wrap stand-alone images https://discourse.gohugo.io/t/remove-empty-p-s-from-content/42462/7?u=harrycresswell
[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = "Index"
url = "/"
weight = 5

[[menu.main]]
name = "Writing"
url = "/writing/"
weight = 10

[[menu.main]]
name = "Links"
url = "/links/"
weight = 15

[[menu.main]]
name = "Topics"
url = "/topics/"
weight = 20

[[menu.footer]]
name = "Index"
url = "/"
weight = 5

[[menu.footer]]
name = "Writing"
url = "/writing/"
weight = 10

[[menu.footer]]
name = "Links"
url = "/links/"
weight = 15

[[menu.footer]]
name = "Topics"
url = "/topics/"
weight = 20

[[menu.footer]]
name = "Slashes"
url = "/slashes/"
weight = 25
